const { Bixby, isPrivate }  = require('../lib/');
const {WAConnection, MessageOptions, MessageType, Mimetype, Presence} = require('@whiskeysockets/baileys');
const fs = require('fs');
const axios = require('axios');

Bixby(
  {
    pattern: "glue",
    fromMe: isPrivate,
    desc: "To check ping",
    type: "user",
  },
   async(conn,match) => {
   match = match[1] 
   if (!match) return await conn.reply('_Need query_');
   var webimage = await axios.get(`https://api.ibeng.tech/api/textpro/neon-light?text=${match[1]}&apikey=tamvan`);
   await conn.sendMessage(conn.chatld, webimage, {}, 'image' , { caption: 'generated by whatsbixby'})
});
